version: "3.3"

networks:
  taiga_network:
      driver: overlay
      attachable: true
  http_network:
    external: true

configs:
    django_settings:
        external: true
    django_celery_settings:
        external: true
    caddyfile:
        external: true
    front_json:
        external: true
    crontab:
        external: true
    taiga_ssh_authorized_keys:
        external: true

secrets:
    taiga-back-celery-settings-orus-io:
        external: true
    taiga-back-settings-orus-io:
        external: true
    taiga-back-events-config:
        external: true

volumes:
    taiga-back-static:
    taiga-back-media:
    taiga-back-postgres:

services:

    ssh:
        image: dockerhub.xcg.io/cloudcrane/alpine-ssh:latest
        networks:
            - taiga_network
        ports:
            - 2201:22
        configs:
            - source: taiga_ssh_authorized_keys
              target: /home/anon/.ssh/authorized_keys
              uid: "133742"
              gid: "133742"
              mode: 0600
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.labels.taiga == 1

    postgres:
        restart: always
        image: postgres:9.6-alpine
        tty: true
        stdin_open: true
        environment:
            - POSTGRES_PASSWORD=taiga
            - POSTGRES_USER=taiga
            - POSTGRES_DB=taiga
        networks:
            - taiga_network
        volumes:
            - taiga-back-postgres:/var/lib/postgresql/data
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.labels.taiga == 1

    django:
        restart: always
        image: registry.orus.io/taiga-back:3.4.0_2bf64a8f_timetracking_0.2.2_4f1005b_s3
        networks:
            - taiga_network
        depends_on:
            - rabbitmq
            - redis
        volumes:
            - taiga-back-static:/usr/django/app/static
            - taiga-back-media:/usr/django/app/media
        configs:
              - source: django_settings
                target: /usr/django/app/settings/local.py
              - source: django_celery_settings
                target: /usr/django/app/settings/celery_local.py
        secrets:
            - source: taiga-back-settings-orus-io
            - source: taiga-back-celery-settings-orus-io
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.labels.taiga == 1

    celery:
        restart: always
        image: registry.orus.io/taiga-back:3.4.0_2bf64a8f_timetracking_0.2.2_4f1005b_s3
        user: django
        entrypoint: /usr/local/bin/celery
        command: -A taiga worker -c 4 -l INFO -Q tasks,transient
        networks:
            - taiga_network
        depends_on:
            - rabbitmq
            - redis
        volumes:
            - taiga-back-static:/usr/django/app/static
            - taiga-back-media:/usr/django/app/media
        configs:
              - source: django_settings
                target: /usr/django/app/settings/local.py
              - source: django_celery_settings
                target: /usr/django/app/settings/celery_local.py
        secrets:
            - source: taiga-back-settings-orus-io
            - source: taiga-back-celery-settings-orus-io
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.labels.taiga == 1

    notifications:
        restart: always
        image: registry.orus.io/taiga-back:3.4.0_2bf64a8f_timetracking_0.2.2_4f1005b_s3
        entrypoint: /usr/sbin/cron
        command: -f
        networks:
            - taiga_network
        depends_on:
            - rabbitmq
            - redis
        volumes:
            - taiga-back-static:/usr/django/app/static
            - taiga-back-media:/usr/django/app/media
        configs:
              - source: django_settings
                target: /usr/django/app/settings/local.py
              - source: django_celery_settings
                target: /usr/django/app/settings/celery_local.py
              - source: crontab
                target: /etc/crontab
        secrets:
            - source: taiga-back-settings-orus-io
            - source: taiga-back-celery-settings-orus-io
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.labels.taiga == 1

    rabbitmq:
        restart: always
        image: rabbitmq:3.6-alpine
        hostname: taiga
        networks:
            - taiga_network
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.labels.taiga == 1

    redis:
        restart: always
        image: redis:4-alpine
        networks:
            - taiga_network
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.labels.taiga == 1

    taiga_events:
        restart: always
        image: registry.orus.io/taiga-events:_3583834
        tty: true
        stdin_open: true
        secrets:
            - source: taiga-back-events-config
              target: config.json
        networks:
            - taiga_network
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.labels.taiga == 1

    caddy:
        restart: always
        image: registry.orus.io/taiga-front:3.4.0_0f6220f4
        tty: true
        stdin_open: true
        depends_on:
            - django
            - taiga_events
        networks:
            - taiga_network
            - http_network
        volumes:
            - taiga-back-static:/srv/taiga-back-static
            - taiga-back-media:/srv/taiga-back-media
        configs:
            - source: caddyfile
              target: /etc/caddy/Caddyfile
            - source: front_json
              target: /srv/taiga-front/conf.json
        deploy:
            mode: replicated
            replicas: 1
            labels:
                - traefik.enable=true
                - traefik.frontend.rule=Host:project.orus.io
                - traefik.port=7416
                - traefik.docker.network=http
            placement:
                constraints:
                    - node.labels.taiga == 1
