version: "3.3"

networks:
  taiga_network:
      driver: overlay
      attachable: true
  http_network:
    external: true
  pgsql_ha_9-6:
    external: true

configs:
    django_settings:
        file: ./back/local.py
    django_celery_settings:
        file: ./back/celery_local.py
    caddyfile:
        file: ./front/Caddy/Caddyfile
    front_json:
        file: ./front/conf.json
    crontab:
        file: ./back/crontab

secrets:
    taiga-back-celery-settings-orus-io:
        external: true
    taiga-back-settings-orus-io:
        external: true
    taiga-events-config:
        external: true

volumes:
    taiga-back-static:
    taiga-back-media:

services:

    django:
        restart: always
        image: registry.orus.io/taiga-back:3.4.0_2bf64a8f_timetracking_0.2.2_4f1005b
        networks:
            - taiga_network
            - pgsql_ha_9-6
        depends_on:
            - rabbitmq
            - redis
        volumes:
            - taiga-back-static:/usr/django/app/static
            - taiga-back-media:/usr/django/app/media
        configs:
              - source: django_settings
                target: /usr/django/app/settings/local.py
              - source: django_celery_settings
                target: /usr/django/app/settings/celery_local.py
        secrets:
            - source: taiga-back-settings-orus-io
        deploy:
            mode: replicated
            replicas: 1

    celery:
        restart: always
        image: registry.orus.io/taiga-back:3.4.0_2bf64a8f_timetracking_0.2.2_4f1005b
        user: django
        entrypoint: /usr/local/bin/celery
        command: -A taiga worker -c 4 -l INFO -Q tasks,transient
        networks:
            - taiga_network
            - pgsql_ha_9-6
        depends_on:
            - rabbitmq
            - redis
        volumes:
            - taiga-back-static:/usr/django/app/static
            - taiga-back-media:/usr/django/app/media
        configs:
              - source: django_settings
                target: /usr/django/app/settings/local.py
              - source: django_celery_settings
                target: /usr/django/app/settings/celery_local.py
        secrets:
            - source: taiga-back-settings-orus-io
            - source: taiga-back-celery-settings-orus-io
        deploy:
            mode: replicated
            replicas: 1

    notifications:
        restart: always
        image: registry.orus.io/taiga-back:3.4.0_2bf64a8f_timetracking_0.2.2_4f1005b
        entrypoint: /usr/sbin/cron
        command: -f
        networks:
            - taiga_network
            - pgsql_ha_9-6
        depends_on:
            - rabbitmq
            - redis
        volumes:
            - taiga-back-static:/usr/django/app/static
            - taiga-back-media:/usr/django/app/media
        configs:
              - source: django_settings
                target: /usr/django/app/settings/local.py
              - source: django_celery_settings
                target: /usr/django/app/settings/celery_local.py
              - source: crontab
                target: /etc/crontab
        secrets:
            - source: taiga-back-settings-orus-io
        deploy:
            mode: replicated
            replicas: 1

    rabbitmq:
        restart: always
        image: rabbitmq:3.6-alpine
        hostname: taiga
        networks:
            - taiga_network
        deploy:
            mode: replicated
            replicas: 1

    redis:
        restart: always
        image: redis:4-alpine
        networks:
            - taiga_network
        deploy:
            mode: replicated
            replicas: 1

    taiga_events:
        restart: always
        image: registry.orus.io/taiga-events:_3583834
        tty: true
        stdin_open: true
        secrets:
            - source: taiga-events-config
              target: config.json
        networks:
            - taiga_network
        deploy:
            mode: replicated
            replicas: 1

    caddy:
        restart: always
        image: registry.orus.io/taiga-front:3.4.0_889736a6
        tty: true
        stdin_open: true
        depends_on:
            - django
            - taiga_events
        networks:
            - taiga_network
            - http_network
        volumes:
            - taiga-back-static:/srv/taiga-back-static
            - taiga-back-media:/srv/taiga-back-media
        configs:
            - source: caddyfile
              target: /etc/caddy/Caddyfile
            - source: front_json
              target: /srv/taiga-front/conf.json
        deploy:
            mode: replicated
            replicas: 1
            labels:
                - traefik.enable=true
                - traefik.frontend.rule=Host:project.orus.io
                - traefik.port=7416
                - traefik.docker.network=http_network
