version: "3.3"

networks:
  taiga_network:
      driver: overlay
      attachable: true
  http_network:
    external: true

configs:
    django_settings:
        file: ./local.py
    caddyfile:
        file: ./Caddy/Caddyfile
    front_json:
        file: ./front/conf.json

volumes:
    taiga-back-postgres:
    taiga-back-static:
    taiga-back-media:
    taiga-rabbitmq:

services:

    postgres:
        restart: always
        image: postgres:9.6-alpine
        tty: true
        stdin_open: true
        environment:
            - POSTGRES_PASSWORD=taiga
            - POSTGRES_USER=taiga
            - POSTGRES_DB=taiga
        networks:
            - taiga_network
        volumes:
            - taiga-back-postgres:/var/lib/postgresql/data
        deploy:
            mode: replicated
            replicas: 1

    django:
        restart: always
        image: registry.orus.io/taiga-back
        tty: true
        stdin_open: true
        networks:
            - taiga_network
        depends_on:
            - postgres
            - rabbitmq
        volumes:
            - taiga-back-static:/usr/django/app/static
            - taiga-back-media:/usr/django/app/media
        configs:
              - source: django_settings
                target: /usr/django/app/settings/local.py
        deploy:
            mode: replicated
            replicas: 1

    rabbitmq:
        restart: always
        image: rabbitmq:3.6-alpine
        hostname: taiga
        networks:
            - taiga_network
        volumes:
            - taiga-rabbitmq:/var/lib/rabbitmq
        deploy:
            mode: replicated
            replicas: 1

    caddy:
        restart: always
        image: registry.orus.io/taiga-front
        tty: true
        stdin_open: true
        depends_on:
            - django
        networks:
            - taiga_network
            - http_network
        volumes:
            - taiga-back-static:/srv/taiga-back-static
            - taiga-back-media:/srv/taiga-back-media
        configs:
            - source: caddyfile
              target: /etc/caddy/Caddyfile
            - source: front_json
              target: /srv/taiga-front/conf.json
        deploy:
            mode: replicated
            replicas: 1
            labels:
                - traefik.enable=true
                - traefik.frontend.rule=Host:tg.chailloux.me
                - traefik.port=7416
                - traefik.docker.network=http_network
