version: "3.3"

networks:
  taiga_network:
      driver: overlay
      attachable: true
  http_network:
    external: true
  pgsql_ha_9-6:
    external: true

configs:
    django_settings:
        file: ./local.py
    django_celery_settings:
        file: ./celery_local.py
    taiga_events_conf:
        file: ./taiga-events/config.json
    caddyfile:
        file: ./Caddy/Caddyfile
    front_json:
        file: ./front/conf.json

volumes:
    taiga-back-postgres:
    taiga-back-static:
    taiga-back-media:
    taiga-rabbitmq:
    taiga-redis:

services:

    django:
        restart: always
        image: registry.orus.io/taiga-back
        networks:
            - taiga_network
            - pgsql_ha_9-6
        depends_on:
            - rabbitmq
            - redis
        volumes:
            - taiga-back-static:/usr/django/app/static
            - taiga-back-media:/usr/django/app/media
        configs:
              - source: django_settings
                target: /usr/django/app/settings/local.py
              - source: django_celery_settings
                target: /usr/django/app/settings/celery_local.py
        deploy:
            mode: replicated
            replicas: 1

    celery:
        restart: always
        image: registry.orus.io/taiga-back
        user: django
        entrypoint: /usr/local/bin/celery
        command: -A taiga worker -c 4 -l INFO -Q tasks,transient
        networks:
            - taiga_network
            - pgsql_ha_9-6
        depends_on:
            - rabbitmq
            - redis
        volumes:
            - taiga-back-static:/usr/django/app/static
            - taiga-back-media:/usr/django/app/media
        configs:
              - source: django_settings
                target: /usr/django/app/settings/local.py
              - source: django_celery_settings
                target: /usr/django/app/settings/celery_local.py
        deploy:
            mode: replicated
            replicas: 1

    rabbitmq:
        restart: always
        image: rabbitmq:3.6-alpine
        hostname: taiga
        networks:
            - taiga_network
        volumes:
            - taiga-rabbitmq:/var/lib/rabbitmq
        deploy:
            mode: replicated
            replicas: 1

    redis:
        restart: always
        image: redis:4-alpine
        networks:
            - taiga_network
        volumes:
            - taiga-redis:/data
        deploy:
            mode: replicated
            replicas: 1
        configs:
              - source: taiga_events_conf
                target: /srv/taiga-events/config.json

    taiga_events:
        restart: always
        image: registry.orus.io/taiga-events
        tty: true
        stdin_open: true
        networks:
            - taiga_network

    caddy:
        restart: always
        image: registry.orus.io/taiga-front
        tty: true
        stdin_open: true
        depends_on:
            - django
            - taiga_events
        networks:
            - taiga_network
            - http_network
        volumes:
            - taiga-back-static:/srv/taiga-back-static
            - taiga-back-media:/srv/taiga-back-media
        configs:
            - source: caddyfile
              target: /etc/caddy/Caddyfile
            - source: front_json
              target: /srv/taiga-front/conf.json
        deploy:
            mode: replicated
            replicas: 1
            labels:
                - traefik.enable=true
                - traefik.frontend.rule=Host:tg.chailloux.me
                - traefik.port=7416
                - traefik.docker.network=http_network
